version: '3.8'

services:
  mysql:
    image: registry.cn-heyuan.aliyuncs.com/libihao/mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1qazZAQ!hhh333
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10  
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1G

  redis:
    image: registry.cn-heyuan.aliyuncs.com/libihao/redis:latest
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 384M

  rabbitmq:
    image: registry.cn-heyuan.aliyuncs.com/libihao/rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 30s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 384M

  platform-web:
    image: registry.cn-heyuan.aliyuncs.com/lsbc/platform-web:1
    container_name: platform-web
    ports:
      - "80:8080"
    depends_on:
      admin-api:
        condition: service_started
      platform-api:
        condition: service_started
      ai-api:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 384M

  admin-api:
    image: registry.cn-heyuan.aliyuncs.com/lsbc/admin-api:1
    container_name: admin-api
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "5158:5158"
      - "5159:5159"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./data/logs/admin-api:/app/logs
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 768M

  platform-api:
    image: registry.cn-heyuan.aliyuncs.com/lsbc/platform-api:1
    container_name: platform-api
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5157:5157"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./data/logs/platform-api:/app/logs
      - ./config/platform-api/appsettings.Docker.json:/app/appsettings.Docker.json
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 768M

  ai-api:
    image: registry.cn-heyuan.aliyuncs.com/lsbc/ai-api:1
    container_name: ai-api
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "5027:5027"
    volumes:
      - ./data/logs/ai-api:/app/logs
      - ./data/ai-models:/app/Model
    deploy:
      resources:
        limits:
          cpus: '1.0'   
          memory: 1.5G   

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:
