apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: lesi-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: registry.cn-heyuan.aliyuncs.com/libihao/mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1qazZAQ!hhh333"
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      volumes:
      - name: mysql-data
        hostPath:
          path: /data/mysql
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: lesi-platform
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306