apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-web
  namespace: lesi-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-web
  template:
    metadata:
      labels:
        app: platform-web
    spec:
      containers:
      - name: platform-web
        image: registry.cn-heyuan.aliyuncs.com/lsbc/platform-web:1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: platform-web
  namespace: lesi-platform
spec:
  type: NodePort
  selector:
    app: platform-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080