apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: lesi-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: registry.cn-heyuan.aliyuncs.com/libihao/rabbitmq:3-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "admin"
        - name: RABBITMQ_DEFAULT_PASS
          value: "password"
        ports:
        - containerPort: 5672
        - containerPort: 15672
        resources:
          limits:
            cpu: "0.5"
            memory: 512Mi
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-data
      volumes:
      - name: rabbitmq-data
        hostPath:
          path: /data/rabbitmq
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: lesi-platform
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672