apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: lesi-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: registry.cn-heyuan.aliyuncs.com/libihao/redis:latest
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.5"
            memory: 512Mi
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
      - name: redis-data
        hostPath:
          path: /data/redis
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: lesi-platform
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379